# Generated by Django 6.1 on 2026-08-11 15:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='lsaprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='lsaprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='lsa_profiles', to='users.skill'),
        ),
    ]
