# Generated by Django 6.1 on 2026-08-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_skill_remove_lsaprofile_skills_lsaprofile_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
