# Generated by Django 6.1 on 2026-08-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('users', '0003_alter_skill_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_end_after_start',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('start_time', models.F('end_time')), _negated=True), name='booking_end_not_equal_start'),
        ),
    ]
